In [1]:
#  NN: 2 inputs, hidden layer, with 2 neurons, 1 output
#  6 weights, 3 biases, 3 weighted sums, 3 activation functions


### Inputs, Weights, Biases, Weighted Sums, Activation Functions 

In [2]:
import numpy as np

#  randomly initialize biases
weights =np.round(np.random.uniform(size = 6), decimals=2) 
biases = np.round(np.random.uniform(size = 3), decimals= 2)

print(f'Weights {weights}')
print(f'Biases {biases}')

Weights [0.16 0.48 0.89 0.54 0.74 0.75]
Biases [0.49 0.66 0.69]


In [3]:
#  inputs  and weighted sums
x_1 = 0.5
x_2 = 0.85

z_11 = x_1*weights[0] + x_2* weights[1] + biases[0]
z_12 = x_1 *weights[2] + x_2* weights[3] + biases[1]

print(f'Weighted sum 1: {z_11}')
print(f'Weighted sum 2: {z_12}')


Weighted sum 1: 0.978
Weighted sum 2: 1.564


In [4]:
#  activation functions in the  hidden layer
a_11 = 1/(1+np.exp(-z_11))
a_12 = 1/(1+np.exp(-z_12))
print(a_11)
print(a_12)

0.7267111924225421
0.82692657787722


In [5]:
# weighted sum in the output layer
z_2 = a_11*weights[4] + a_12*weights[5] + biases[2]
print(z_2)

1.8479612158005962


In [6]:
# activation function in the output layer
a_2 = 1/(1+np.exp(-z_2))
print(a_2)

0.863887548619393


### Artificial Neural Networks

In [7]:
n = 2 # number of inputs
num_hidden_layers = 2 # number of hidden layers
m = [2, 2] # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer

In [8]:
import numpy as np # import the Numpy library

num_nodes_previous = n # number of nodes in the previous layer

network = {} # initialize network an an empty dictionary

# loop through each layer and randomly initialize the weights and biases associated with each node
# notice how we are adding 1 to the number of hidden layers in order to include the output layer
for layer in range(num_hidden_layers + 1): 
    
    # determine name of layer
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
    
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network

{'layer_1': {'node_1': {'weights': array([0.26, 0.76]), 'bias': array([0.02])}, 'node_2': {'weights': array([0.17, 0.82]), 'bias': array([0.43])}}, 'layer_2': {'node_1': {'weights': array([0.74, 0.44]), 'bias': array([0.96])}, 'node_2': {'weights': array([0.17, 0.11]), 'bias': array([0.7])}}, 'output': {'node_1': {'weights': array([0.15, 0.81]), 'bias': array([0.15])}}}


In [9]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [10]:
# small network with 5 inputs, 3 hidden layers, 3 nodes in the first layer, 2nodes in the second and 3 nodes in the third layer, 1 node in the output
small_network = initialize_network(5, 3, [3,2,3], 1)

In [11]:
small_network

{'layer_1': {'node_1': {'weights': array([0.73, 0.94, 0.03, 0.19, 0.72]),
   'bias': array([0.6])},
  'node_2': {'weights': array([0.34, 0.46, 0.31, 0.98, 0.67]),
   'bias': array([0.88])},
  'node_3': {'weights': array([0.05, 0.83, 0.67, 0.76, 0.35]),
   'bias': array([0.15])}},
 'layer_2': {'node_1': {'weights': array([0.49, 0.35, 0.27]),
   'bias': array([0.77])},
  'node_2': {'weights': array([0.22, 0.15, 0.4 ]), 'bias': array([0.56])}},
 'layer_3': {'node_1': {'weights': array([0.77, 0.51]), 'bias': array([0.72])},
  'node_2': {'weights': array([0.82, 0.4 ]), 'bias': array([0.82])},
  'node_3': {'weights': array([0.18, 0.82]), 'bias': array([0.49])}},
 'output': {'node_1': {'weights': array([0.71, 0.72, 0.04]),
   'bias': array([0.25])}}}

In [12]:
def compute_weighted_sum(inputs, weights, biases):
    return np.sum(inputs*weights) + biases

In [13]:
#  generate 5 inputs to feed small_network
from random import seed
np.random.seed(42)

inputs = np.around(np.random.uniform(size=5), decimals = 2)
inputs

array([0.37, 0.95, 0.73, 0.6 , 0.16])

In [14]:
# compute weighted sum in the first node, at the first layer
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']

weighted_sum = compute_weighted_sum(inputs,node_weights, biases)
weighted_sum

array([1.9042, 2.0742, 2.1042])

In [15]:
# compute node activation
def node_activation(weighted_sum):
    return 1/(1+np.exp(-1* weighted_sum))


In [16]:
node_output = node_activation(weighted_sum)
node_output

array([0.87036614, 0.88837015, 0.89131073])

### Forward Propagation


In [17]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [19]:
predictions =forward_propagate(small_network, inputs)

The outputs of the nodes in hidden layer number 1 is [np.float64(0.8823), np.float64(0.9141), np.float64(0.8763)]
The outputs of the nodes in hidden layer number 2 is [np.float64(0.8531), np.float64(0.7759)]
The outputs of the nodes in hidden layer number 3 is [np.float64(0.8548), np.float64(0.8618), np.float64(0.7824)]


In [20]:
predictions

[np.float64(0.8189)]

Deep learning is one of the hottest subjects in data science. 

Color restoration applications can automatically convert a grayscale image into a colored image. 

Speech enactment applications can synthesize audio clips with lip movements in videos, extracting audio from one video and syncing its lip movements with the audio from another video. 

Handwriting generation applications can rewrite a provided message in highly realistic cursive handwriting in a wide variety of styles. 

Deep learning algorithms are largely inspired by the way neurons and neural networks function and process data in the brain. 

The main body of a neuron is the soma, and the extensive network of arms that stick out of the body are called dendrites. The long arm that sticks out of the soma in the other direction is called the axon.  

Whiskers at the end of the axon are called the synapses.  

Dendrites receive electrical impulses that carry information from synapses of other adjoining neurons. Dendrites carry the impulses to the soma.  

In the nucleus, electrical impulses are processed by combining them, and then they are passed on to the axon. The axon carries the processed information to the synapses, and the output of this neuron becomes the input to thousands of other neurons. 

Learning in the brain occurs by repeatedly activating certain neural connections over others, and this reinforces those connections. 

An artificial neuron behaves in the same way as a biological neuron. 

The first layer that feeds input into the neural network is the input layer. 

The set of nodes that provide network output is the output layer.