In [1]:
import torch as t

In [2]:
# y = -1 +2x

w = t.tensor(2.0, requires_grad=True)
b = t.tensor(-1.0, requires_grad=True)


In [3]:
def forward(x):
    y_hat = b+ w*x
    return y_hat

In [4]:
# Predict y = 2x - 1 at x = 1

x = t.tensor([[1.0]])
y_hat = forward(x)
print(y_hat)

tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
# Create x Tensor and check the shape of x tensor

x = t.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 1])


In [6]:
# Make the prediction of y = 2x - 1 at x = [1, 2]

yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [ ]:
#  Class Linear
from torch.nn import Linear

In [8]:
t.manual_seed(42)

In [10]:
lr = Linear(in_features=1, out_features=1, bias = True)
print(list(lr.parameters()))

[Parameter containing:
tensor([[-0.2343]], requires_grad=True), Parameter containing:
tensor([0.9186], requires_grad=True)]


In [11]:
# state_dict
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict({'weight': tensor([[-0.2343]]), 'bias': tensor([0.9186])})
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[-0.2343]]), tensor([0.9186])])


In [ ]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[-0.2343]], requires_grad=True)
bias: Parameter containing:
tensor([0.9186], requires_grad=True)


In [13]:
#  make a single prediction at x = 1.0
x = t.tensor([[1.0]])
y_hat = lr(x)
print(y_hat)

tensor([[0.6843]], grad_fn=<AddmmBackward0>)


In [ ]:
#  create multiple predictions
x = t.tensor([[1.0], [2.0]])
y_hat = lr(x)
print(y_hat)


tensor([[0.6843],
        [0.4501]], grad_fn=<AddmmBackward0>)


In [15]:
# custom modules
from torch import nn

In [16]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        # inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out




In [17]:
lr = LR(1,1)
print(list(lr.parameters()))
print(lr.linear)

[Parameter containing:
tensor([[-0.2191]], requires_grad=True), Parameter containing:
tensor([0.2018], requires_grad=True)]
Linear(in_features=1, out_features=1, bias=True)


In [18]:
x = t.tensor([[1.0]])
y_hat = lr(x)
print(y_hat)

tensor([[-0.0173]], grad_fn=<AddmmBackward0>)


In [19]:
x = t.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.0173],
        [-0.2364]], grad_fn=<AddmmBackward0>)
